### ISSUE TITLE
Allow install dir to be overriden

### ISSUE THREAD

**Issue by Baggypants** [brummer10/XPolyMonk.lv2#1]
Change the Makefile variable definition from = to ?= to allow overrides

```
diff --git a/XPolyMonk/Makefile b/XPolyMonk/Makefile
index 49302b7..ff5b3e4 100644
--- a/XPolyMonk/Makefile
+++ b/XPolyMonk/Makefile
@@ -3,9 +3,9 @@
        # check if user is root
        user = $(shell whoami)
        ifeq ($(user),root)
-       INSTALL_DIR = /usr/lib/lv2
+       INSTALL_DIR ?= /usr/lib/lv2
        else
-       INSTALL_DIR = ~/.lv2
+       INSTALL_DIR ?= ~/.lv2
        endif

        # check CPU and supported optimization flags
```

**Comment by brummer10** [comment]
Hi
Well, I could do that. Just note that you could overwrite it as well like it is by give the INSTALL_DIR parameter on the command-line. 
`make install INSTALL_DIR=my/path/to/.lv2`

Without the `?` it will just not automatically overwritten by a Environment Variable with that name.

**Comment by Baggypants** [comment]
Makefiles are not my strong suit, I wasn't familiar with that functionality.
